### PR TITLE
transport concept

### PR DESCRIPTION
**Pull request by GGAlanSmithee**

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
Just a draft for now @brokenprogrammer, I will add more docs before merge, but feel free to read these as I update this PR.

**Comment by GGAlanSmithee** [comment]
@brokenprogrammer this is ready for review now

**Review by brokenprogrammer — APPROVED** [review]
Interesting stuff!

**Comment by GGAlanSmithee** [comment]
Thanks m8!

**Pull request merged**
